# Designing a research project 



Hi, everyone, and thank you for joining me for the week 3 lecture on designing a research project. My name is Martin and I’m the course coordinator SLAT7806. With me in the teaching team is Amir who is delivering the Wednesday tutorial. So as in week 3, we're going to start with a quick refresher on the research process. And we're going to remind ourselves that planning and designing is the second step in the research process. And that involves choosing and devising appropriate research methodology in relation to your research question, of course, and obtaining ethical clearance.

So to break it down even further, today, we're going to talk about how to start planning and designing a research project. We're also going to introduce through different study design types, such as qualitative and quantitative research and cross sectional and longitudinal studies. We're also going to talk about research methodology components, such as participants, materials, and procedures. Then we're going to explore the relationship between your research question and your method and we're going to find out that it's not a one to one correlation. Then we will discuss ethical considerations that need to be taken into account when you design a research project. And finally, we're going to conclude by talking briefly about rating and structuring your Methods section.

Let's begin by talking about first steps in project design. So your project design should depend on a few very important things. The first one, which as you guessed, is your research question, remind yourself what the purpose of your study is, what it is exactly that you would like to investigate. And based on that you can start thinking about the research methodology. 

So for instance, if your aim is to investigate differences between native speakers and learners of English, we need to analyze both native speakers and learners – not just native speakers OR learners. Also, you obviously also need to consult previous literature, what have other researchers used to answer similar questions. 

So keeping up with the example of differences between native speakers and learners of English, when other researchers investigated that topic, what factors have they paid attention to? For example, the years of instruction? Or maybe some other things? Here, you can also pay attention to what tools they have used to investigate that particular question. Did they interview learners and native speakers, have they used experiments or have they used corpus data? 

Finally, on the practical side of things, you need to take into consideration the resources that are available to you. And so these would be things like time: does your project have a due date? Do you have these available funding, equipment, and also skills that you currently possess or accessibility of necessary training?

Now, let’s talk about different study design types.

As you might have already guessed, steady design types are extremely varied and diverse. So the handy way of looking at them is to group them in broader categories. And two of those product categories are cross sectional and longitudinal design studies. So a cross sectional study tests a large group of participants at a single point in time. So say we're interested in measuring vocabulary size of 200 5 year old English speaking children. That's a cross sectional study, because after measuring the vocabulary size once, we're not following up on those children. Longitudinal studies, on the other hand, commonly look at smaller group of participants, but they're tested over a period of time. 

So here once again, we may be interested in measuring vocabulary size, but instead of doing it was 200 children, we're only testing 20 English speaking children and record them repeatedly from when they are 1 until they are 10 years of age. And we're administering this test to them once a year. So what's really interesting in this scenario is that in both cases, we will end up with 200 observations. 

Both study types in this case allow us to study the development over time and it depends on other factors which design we choose. Longitudinal studies often take much longer and participants drop out – which would speak to for a cross-sectional design – but longitudinal studies are better at allowing us to analyze how individuals change over time. So, both designs have their advantages and disadvantages. 

Another broad distinction that we can make between study designs is to look at qualitative and quantitative research. Both of those approaches have their advantages and disadvantages. So, qualitative approach better able to take context into account and may be better at giving a more complete picture of what is going on in a social setting. It also allows additional issues and questions to emerge when collecting data. 

However, because it is more exploratory it may be difficult to replicate, it is also hard to generalize from one setting to another, because they may be pretty different and dependent on the subjects. Also, qualitative studies are typically subjective, because the researcher ends up immersing themselves into the setting and we cannot say what factors are more important than others.

Quantitative studies, on the other hand, are very objective and replicable. Another researcher can repeat the same study in exactly the same way and expect to obtain the same results. It is also generalizable; the findings can be extrapolated beyond the tested population and we can determine how strongly each factor affects an outcome. 

Among the disadvantages of the quantitative research is, however, that it is extremely focused. So, the researcher is looking only at the factors that are included in the study and may miss other useful factors and insights. A lot of people also say that quantitative approach is more daunting and requires training to perform statistical analyses properly. When conducting experiments, the setting can also be artificial, which means that it's carried out in a controlled environment which calls into question if the behavior in such a setting is natural and can be generalized to natural behavior.

As you can see, both qualitative and quantitative approaches or study designs have something important to contribute to our understanding of the processes of analyzing language. So, the best way forward is not to focus on one or the other, but to combine them when you design your own study. 

When you begin tackling, planning and designing your research project, you may want to break up your research design into smaller building blocks, such as your participants, materials, and procedures – and this is what we will talk about now.

In this section, we're going to talk about those building blocks one by one, starting with participants. Sometimes they're also referred to as subjects or informants in research literature. So here, your main task is to decide whether you're going to recruit one or multiple groups and what those groups are going to be like. So, let's start with the first scenario. If you're recruiting one group of participants, you need to make sure that this group is representative of the wider population under investigation, which means that this group needs to be both diverse and homogenous.

Let's take an example of being interested in studying L2 Japanese acquisition in Australian universities. So here to address this research topic, you can recruit adults of various ages, genders and backgrounds. But they all have to be learning Japanese in the context of an Australian University. So, in slide 10, the aspects highlighted in blue, there is ages, genders and backgrounds, accounts for the diversity of your sample, and it means that they're going to be very likely similar to a wider population of second language Japanese learners, and the part that is highlighted in green. 

All of your participants have to be learning Japanese in Australian University which ensures that your sample has something in common and also provides for a very specific research question. If your participant sample is too diverse, it becomes hard to distinguish among factors that explain the observed phenomenon. So, for instance, if you see a lot of variation in second language Japanese learners in Australian universities, you may want to trim back your sample and maybe just look at various ages and genders, but focus on a single background. 

On the other hand, if your sample is too homogenous, it is difficult to make generalizations. So let's imagine that you're only testing young adult females acquiring second language Japanese, in Australian universities, we may not be representative of the entire population of Japanese learners, and therefore the findings that you obtained from that study, maybe questioned by the research community.

If you're comparing multiple groups, ideally, you would need to ensure that the groups only differ in one aspect or independent variable, but are similar otherwise. So once again, here we're interested in second language acquisition of English and we recruited two groups of English learners, both of which are speakers of Mandarin Chinese are their native language, they have similar English proficiency, which is determined by the IELTS scores, for example. They're within the comparable age range, and will also have an equal or roughly equal number of males and females and each group. 


So so far, these groups are very comparable, but they have different length of residence in Australia. So, keeping the difference to this one independent variable ensures that whatever differences we are finding between those two groups can be attributed to this particular variable. So, when you think about participant recruitment, you need to specify participation criteria for each group. And basically, what that would mean is that some groups will be included in your study, but also some groups would be excluded in linguistics research. 

Okay, so now we're moving on from participants to materials, which are sometimes also referred to as stimuli in research literature. So, your materials, account for anything that your participants are presented with when they come in to participate in your study. It could be a set of questions, a list of words or sentences, pictures, audio recordings, video recordings, problem sets, stories, etc.

Here you need to provide detailed description and examples of your materials set to ensure that your study is replicable by other researchers. It is also very common to provide a full list of materials as an appendix of the paper so that your readers not only see some examples, but they can estimate the size of your material set the order in which the materials are presented, and they can build their materials to match your previous study. And then the procedure ties the participants and the materials together. 

Basically, your procedure answers the question of how your participants are supposed to engage with the materials that you're providing them with. For example, if you have a sentence list, the question you need to address here
is whether your participants are required to listen to the sentences or maybe to produce them out loud. Your procedure also answers the question of what tasks your participants are required to complete. 

So, for instance, if we have decided that your participants will need to listen to the sentences, what do they do exactly while listening. So, in this example, they will need to press a button every time they think there is a grammatical error in a sentence that they're listening to. Then you need to describe what is the purpose of that task why they are pressing the button. So here we'll assume that this listening task does error detection, accuracy and speed in second language speech perception. 

Finally, we need to describe how exactly the task is set up and completed. And this is the practical side of procedure description. So here you may want to touch on things such as whether the task is completed individually or in groups, what is the setting for task completion? So, for example, a quiet room, what is the equipment that's provided to the participants, how long it takes, etc. This amount of detail once again ensures that your study is replicable and other researchers are able to reproduce your study - that is they do exactly what you have done just on a new set of subjects. 

So, participants, materials, procedure is a very common structure of research design methodology. However, you will also find that there are considerable variations on that structure. For instance, a study investigating how second language Korean textbooks portray Korean culture may not involve participants at all. So here we would identify materials. So, for example we can see which Korean textbooks that have been published in the last decade. And we can also identify the procedure, which in this case could be a content analysis, text analysis or text mining. So, for instance, visualizing frequent words, finding keywords, or extracting topics - but we don't really have participants and we're not measuring their responses – but one could check the amount of interest and the amount of engagement that learners have with those textbooks – which would then be another study using the same materials but now with participants. 

So, the key takeaway here is that participants/materials/procedure is the core structure of the Methods section. But there are variations on that as well and it is important to read the existing literature with an open mind to see how people have tried to answer their (research) questions. 

So, at the beginning of this lecture, I emphasized that it's your research question that is determining the selection of your methodology. In this part, we're going to explore this relationship between a research question and a selected method. A research question without a doubt informs the selection of the methodology. However, it is also possible to address the same question using different methods. 

An example here we want to analyze the attention that is paid to grammatical errors. In second language research, speech perception can be examined by a number of different tasks or methods. One of those tasks we have already discussed today. So, if we look at conscious awareness of grammatical errors, we may want to administer a listening task to participants where they would be required to listen to the sentences and press a button when they hear an error. What this would measure is the accuracy and the speed with which a participant can distinguish between an error free sentence and the sentence that has an error. 

But we can also address this same question subconsciously, by using electroencephalography or EEG for short. So to conduct this task, we invite a participant and we administer a EEG cap. Basically, this cap has a number of different sensors to which electrodes are connected. And those electrodes are measuring the electrical activity in our brain when certain stimuli are presented to the participant. After that cap is fitted, the participant is presented with a set of sentences to listen to. And some of those sentences contain errors, while others are error free. But the participant does not receive any explicit instructions to pay attention to errors. They just ought to listen to the sentences 

Now what EEG does is to records subconscious reaction of our brain to sentences with errors. And on the figure in slide, here, the line in green represents the reaction to something that's deviant in this speech, i.e., the electric activity in certain parts of the brain when it listens to sentences with errors. And you see how differs from the activity in the same parts of the brain when we are perceiving something that's standard, so sentences without errors (as shown by the black dotted line). 

So, to summarize here, it is, without a doubt possible to address the same research question using different methods. On the other hand, it is also possible to use the same method to address different research questions. Let's look at an interview as a research procedure. So, an interview can be used to get someone's opinion about second language acquisition. We can ask our participants questions like Is it hard to acquire a second language as an adult? Or Do you think it is necessary? 

An interview can also be used to get someone's actual spontaneous speech production and we could then look at whether the speech is fluid and repair free. We could also use interviews to gather data that we can use to examine the accents of second language learners, and things like that. So, our first set of questions would be about attitudes to second language acquisition, and therefore it is more common to analyze such issues using qualitative methods. Our second set of questions would be about the actual second language performance, something that's measurable, quantifiable and therefore, typically analyzed using quantitative methods. 

Now, research ethics is the topic that needs to be considered alongside questions relating to the methodology and design. Researchers often collect primary data, or in other words, information directly from people and when this is part of a research design, we must always consider ethical implications. And we can look at ethics at a variety of different levels. First of all, there is the institutional levels and here we'll look at potential risks and benefits and participants’ privacy and confidentiality. In universities, ethics at institutional levels are managed by human research ethics committees. 

And what you will need to do is before you conduct any study involving human participants, is that you'll need to make an application to obtain ethical clearance. Usually, this process involves a few steps and going back and forth between the researcher and the human research ethics officer. 

At a community level, ethics are also very important to consider, particularly a researcher needs to ensure that they approach any study with respect and consideration for community morals and values. So, for instance, researchers need to consciously avoid certain topics that may be traumatic or inappropriate for a particular cultural group. 

And then finally, at an individual level, it is a researcher’s responsibility to provide their participants with clear participation guidelines. So, no participants should be engaged in a study without knowing how the data is going to be used, what is exactly that they need to do and how their results will be presented to grow the community. No research activity should be undertaken prior to obtaining an informed and signed consent form from the participant which usually contains all of the necessary details about the study. And finally, it is essential to explain to the participant that they have an opportunity to withdraw from the study at any point without risking to taint their relationship with the researcher or their institution. 

Now, we have already been discussing the structure of your literature review, and I'm happy to tell you that the Methods section in the research paper is much more straightforward to write So, the structure of the Methods section follows the structure that we have already discussed. It is separated into subsections, outlining the details of your participants, your materials and your procedure. It is described with sufficient amount of detail and examples to ensure that the undertaking project is replicable by other researchers and that its findings verifiable. 

Individual participant information should never be disclosed in the Methods section, you either present participant details as group results, or if your study focuses on individuals, that identifiable information should be changed. So, for example, you could use an initial instead of providing their real name. Here, I would also like to highlight that even though the participants materials procedure is the usual structure, once again, you may frequently see a variation on that structure, as some people may want to rename one of the subsections but add additional subsections to better represent their research design.


Okay, so let's summarize what we have covered today. research methods are extremely varied and diverse, which makes choosing the best method difficult. But the things you may want to consider is breaking down this decision into choosing the most appropriate participants and their selection criteria. So, who to include in your study and who to exclude? 

You may also want to specify and create a very detailed description of the materials that will be presented to your participants, and then provide a clear detailed account on the procedure. So, the tasks that your participants completed, how those tasks were administered and performed, and what are the purposes of those tasks. 

The choice of research methodology, without a doubt, stems from the research question, however, it is not one to one correspondence. Some questions may be answered using multiple methods, but certain methods may also be appropriate for different questions. So never worry about not necessarily going with the exact same method that previous literature has discussed. 

There is always room for variation and creativity. Finally, in your research undertaking, especially the research projects that involve human participants should follow a strict code of ethics. We'll come back to it again in later weeks. But for now, just remember that you need to always be respectful to the participants and inform them about the purpose of the study and what is expected from their participation. That's it for today. Thank you very much for listening and talk to you again next week. All the best, Martin

