# Ethics and Academic Integrity

-Hi, everyone, I hope you're doing really well. And I would like to welcome you to this week's lecture, in which our focus is on integrity and  ethics.

-As you may have noticed from the lecture title, I deliberately didn't specify that we're going to discuss academic integrity, or research ethics in particular. And the reason for that decision is that in this lecture, we're going to look at integrity and ethical conduct as a broad set of moral values and responsibilities, which should guide all aspects of our individual behavior, as well as in a variety of academic and research practices. 

-So of course, since our interests lie in the areas of language and culture studies, we're going to be looking at ethics and integrity in the research and professional areas of linguistics, and applied linguistics, TESOL, interpreting and translation, we are going to distinguish among the ethical responsibilities we have as researchers, professionals, and students. And we're also going to try and discern what                   kind of responsibilities we have to individuals, whether that's our research participants or clients, to the broader community, external and internal organizations, our colleagues and peers, and to the field in general. 

-As the part of this lecture overview, I’d also like to introduce how we understand integrity in general. So here we talk about integrity, implying honesty and accountability, which gives us credibility in a variety of personal and professional contexts. So basically, when we say that somebody is acting with integrity, we mean that they're accountable, responsible, and trustworthy. 

-There are three components that we can distinguish within that concept of academic integrity. The first one is morality, which means that we understand and subscribe to academic values of right and wrong. So a duty of care, for example, is a good representation of what's considered to be morality in academic integrity. Membership means that we feel the sense of belonging, and we want to contribute to the academic community, through for instance, the process of peer review, offer examples through representing our data in an honest and transparent way. 

-Finally, we'll also talk about mechanics in academic integrity, which means that we know how to research collaborate and work with integrity. For instance, here we talk about things like understanding sources of information and appropriate referencing to those sources. As you can see, these three components morality, membership, and mechanics, are transferable to other areas as well. 

-So whether your aspiration is to become a researcher in the area of languages and cultures, or a professional, teasle practitioner, an interpreter or a translator, all of those areas imply direct contact with people. Therefore, the first set of responsibilities that we need to consider when we talk about ethical conduct is our obligations to individuals. So when we talk about researchers collecting primary data, or practitioners working directly with clients, what we must consider is ethics on three different levels. 

-So the first level is the level of an individual. in research, we talk about our responsibilities to our subjects, informants or participants in teaching about our responsibilities to students. And in interpreting and translation about our responsibilities to service recipients or clients, you can probably see that some of those roles may be completed. So for instance, if a teacher undertakes action research to improve their pedagogical practices, that students become their participants, which may introduce a layer of complexity in the pre existing relationship. That's why considering ethics is very important in this scenario. 

-The next level of consideration is the community societal and cultural level. And here we need to ensure that no community is mis represented throughout research, and that we're sensitive to cultural differences between certain communities. Finally, we need to consider ethics on an institutional level, because different organizations may have different guidelines. 





-So we can have a discussion of the ethical responsibilities to individuals by focusing on a research setting So when we're conducting a research project, the key thing to remember is that we have to have respect for the informants, right sensitivities, privacy, and safety. 

-And our research design has to put those things at the forefront before the research aim or the research objectives of a particular study. So these things include things like how do we ensure that the data that we collect is not identifiable and confidential, or whether the opinions that are expressed by our participants are likely to put them at any risk from the broader community and things like that. 

-In addition to respecting our performance rates, we need to ensure that there is no intended harm or disadvantage to our performance as they're performing the tasks at hand. Sure, some of these studies may have no direct benefit to the participants, but rather aim to advance our overall knowledge. 

-But at least we need to ensure that the participant group that is directly involved in our research is not harmed, as a researcher will also need to be able to anticipate any potential risks that are associated with a research project that we would like to undertake. If such risks are identified, we need to make every attempt to either avoid those risks or discomforts, or to mitigate them as much as we can if they arise. 

-And that requires a flexible approach to conducting research. We're quite lucky in the areas of languages and cultures because our risks are considered to be negligible or minimal. So for instance, one of the discomforts that a participant may experience during a linguistic study is fatigue. If for example, an interview or an experiment goes for too long, and so to mitigate this risk, we may propose breaking up an interview and conducting it on several consecutive days. And other particular risks that we may want to consider is bringing up the topic that can be considered sensitive for certain communities. 

-And so once again, if such risk is identified, we need to provide our potential solutions as to how we may minimize or avoid this risk all together. In general, we should always aim for clear and unambiguous communication about all aspects of the research project. And such communication should take place throughout undertaking of a particular study. 

-So what it means is that we negotiate and then renegotiate, again, the research participation with our informants, we inform them about any potential discomfort, how long the study will take, what are the implications of the study how the data is going to be treated and communicated to the broader community, we need to make it very clear where the results are going to be identifiable, and whether it's possible to trace back the information that they're providing to their identity. 

-So all of those things need to be considered                          prior to designing a study and then clearly laid out for your participant. So there isn't there is an asterisk next to the clear and unambiguous communication about all aspects of the research project is that it's not always possible. And here I'm in particular, talking about the studies that involve distraction, deception and covert research. And on the slide, as you can see, I'm color coding those terms differently distraction being green, meaning that it's more acceptable according to the ethical code of conduct and deception and covert research presenting more of a gray area.

-So basically, what we mean by distraction is that a participant performs a series of tasks during their participation in our study, some of the tasks contribute directly to our understanding of a particular  phenomenon.

-And then some other tasks are there to distract the participant from what they're doing, and therefore to elicit a more natural behavior; deception involves not necessarily disclosing all aspects of the research project to the participant from the get go. But absolutely 100% debriefing them on the research aim after their participation and giving them an opportunity based on the full information to withdraw their consent, and withdraw their data from the data set of the entire project. 

-Covert research similarly, means that we're presenting our participants with a broad aim of a particular project, rather pinpointing a specific things that we're looking for and this is quite cool. Well, once again, we're aiming to try and get natural behaviors. Because if we do specify our particular aim, we may elicit desired behaviors of what are what informants think we wanted to see from them in terms of what opinions they express, or what kinds of things they do in an experimental setting. 

-So once again, to reiterate, distraction, deception and covert research can be employed in a research design in an ethical manner. However, there's should be no intended misleading information that is presented to the participant. And those things should be very carefully incorporated into project and very carefully designed, and the participants should be presented with an opportunity based on the full information to withdraw from a particular study. 

-So in the tutorial, we’re going to give you three examples of linguistic and psychological studies that employ ethical distraction, deception and covert research to give you a more in depth understanding of those three concepts. Obtaining informed consent is at the core of ethical research. And there are a couple of things that you need to remember when we talk about consent. 

-So, after explaining the study, and prior to commencing the data collection, the researcher needs to provide their participants with two documents. So the first document is the information sheet, which presents the explanation of the study that you have already gone through with your participant in writing, the benefit of the information sheet is that it needs to be retained by the participant and so, they always have this reference to look back at and also the contact details of the researchers themselves and also of the human research ethics committee. 

-In case they would like to reach out and express any concerns about how a particular project has been undertaken. And then the second document is the consent form. So it needs to be signed by the participants and retained by the researcher, because the consent form serves as a formal proof that a study that has been undertaken has been undertaken with integrity and in an ethical manner. Two important points to remember and understand here are that no research activity can be undertaken until the written informed consent is obtained. So there may be some cultural differences here in respect obtaining written informed consent, as some cultures have distressed to written documentation, and maybe more willing to provide an oral or verbal informed consent.

-So if that's the case, such changes or this leniency should be reflected in the ethics application form. And the reasons for not being able to obtain the written informed consent should be very clearly outlined and specified. After providing written or verbal consent, participant can still withdraw from the study at any point, without any penalties or consequences. 

-So if their withdrawal should not affect their relationship with the researcher, with the institution that the researcher represents. So this is a very crucial point to remember. withdrawing from a study is absolutely the right of the participant whenever they feel like the study is not going according to what they have anticipated. And so they even can withdraw after going through the information sheet with you and providing their consent for participation.

So when planning and designing a research project, extra care needs to be taken if you're hoping to test or examine vulnerable participant groups, such as the ones that are presented on the slide. So for instance, if you are hoping to work with children and young people, people in countries other than the country where your research originated, and therefore people maybe with low proficiency level in the target language in which the research is undertaken, people independent or unequal relationships, such as the example of an action research undertaken by a teacher with their students, where the students may feel uncomfortable when saying no orr maybe uncomfortable, to withdraw from the study, and also in an Australian context, if you plan to undertake research with Aboriginal and Torres Strait Islander Under people. 

-So if you are hoping to work with one of the vulnerable participant groups, it is possible, it just means that you need to take extra care with research, design and administration, and be aware of the needs of your participant groups as well as some sensitivities that they may have. 

-So  for instance, if you're working with infants, you ensure that your studies are fairly short and straightforward, so that your participants are not overly tired at the end of the study. In case of working with Aboriginal and Torres Strait Islander people, you need to be aware of some of the cultural sensitivities that these populations may have, so that your research is in no way harmful or offensive to those groups. 

-Additionally, extra measures need to be taken to ensure a collection of informed consent. So once again, obviously, when you're working with young children, they may not be able to provide the consent for themselves. So therefore, you may need to seek the consent from their parent or legal guardian. 



-And therefore, the study's design and benefits and outcomes need to be very clearly laid out to the Guardian rather than the child or young infant themselves. If you're, for example, dealing with speakers of a language other than English, if your studies conducted in English and their proficiency level is fairly low, you may need to employ an interpreter as you're explaining the design of the study and the outcomes of the study to your participants. 

-And also, you need to translate all of the relevant study documents such as the information sheet and the consent form, to ensure that when they're signing the consent, it has truly informed and they understand all of the components of their participation. So I think by this point of the lecture, you're able to appreciate how many ethical considerations there are to take into account when designing a research projects that involves human participants. 

-So to keep all of those considerations in check and organized, every researcher before undertaking the study, they need to get it approved by the human research ethics committee, and what they are seeking from this committee is obtaining an ethical clearance to conduct their research. So in this part of the lecture, what we're going to go through are some bits of information that need to be provided to the human research ethics committee, within the context of a university, if you would like to undertake a study involving human performance. 

-So the first thing that you need to specify is your project description in plain language. So you basically need to address the questions of who you're going to test where the study is going to take place, what is the objective and why it is important to conduct your research. You also need to specify your recruitment details and your recruitment strategy. 

-So what are the criteria for the participants that you're aiming to involve in your project, why those particular criteria are essential for the aim of the study, and how you're going to go about recruiting your participants is going to be through word of mouth, or maybe online advertisement and why such recruitment strategies are appropriate and non invasive. 

-You go through the practicalities of your project, such as the timeline and the budget. So the timeline is important, because you need to make sure that your data collection doesn't coincide with, for example, some cultural festivals of a group that you're aiming to recruit. And in terms of budget, you need to specify where the informants are going to be reimbursed for the time and effort for their contribution to the project. 

-And if they're not reimbursed, why that's the case. You need to go through all of the ethical considerations and potential risks that you're able to identify in association with the study you would like to undertake. And you will also need to say how you're going to ensure the confidentiality and privacy of your participants. 

-So this includes during the data collection, so how are your participants going to be identified? Are you going to use a particular code in reference to each participant and things like that, but also you need to talk about how you're going to manage and protect your data. So the general advice here is to always keep your data on an secure computer or a secure cloud storage, and to always protect it with the passwords so that the person who is not familiar with your project can not get access to this sensitive information. 

-Another piece of advice here is to make your data known identity five volt or non real identifiable so that every participant is referred to by a particular code, rather by, for example, their name, and no personal details such as, for example, addresses are stored anywhere on the data storage system. Within your ethical clearance application, you're also expected to provide all relevant documentation that you're going to be using when you're administering your study. 

-So that includes the exact copy of the informed consent that you're planning to present your participants well, as well as any additional information, whether oral or in writing that you intend to provide your participant. So for example, an information sheet is one of those documents that you will be able to provide. And then if you are planning to administer a survey to your participant, you're always in close of the exact survey document that you're going to be presenting your participants with in your ethical clearance application. 



-When you're writing up your ethical application, there is always additional considerations that need to be taken into account for vulnerable groups. Or if you're planning to conduct uncomfortable or invasive procedures, which is more applicable to, for example, medical research rather than research and languages and cultures. 

-But nonetheless, if you are administering a lot of different tasks onto participant groups, and if your study is extra long, this is some things that may contribute to being uncomfortable. And so basically what the human research ethics committee is looking for is whether your study can be classified as being low versus high risk, and the higher the risk, the more rigorous of that acceptance process and the more rounds of revisions, it is likely that the ethical clearance application will go through. 

-So generally speaking to studies and language and cultures go under negligible and low risk categories, which makes the process of ethical clearance fairly straightforward. So what is important to understand here is that applying for an ethical clearance is not a one off thing. So your ethical application is always kept up to date, and renegotiated with human research ethics committee. 

-So what it means is that every year you submit a progress report on how your project is going and whether Everything is going according to plan. And as you're applying for the ethical clearance for the first time, your application goes through a review process. So that means that after your initial application, your study is not immediately accepted, but rather, the human research officer comes back with certain recommendations, suggestions and revisions, and then you update and revise your ethical clearance application based on that. 

-And usually after the first round of review, if you have taken care to really address those comments, then the project is accepted. If you notice yourself that something is not going, as you expected with, for example, participant recruitment or obtaining an informed consent, or, for example, you may need to recruit an extra group of participants, you're always welcome to apply for a project amendment prior to reaching the milestone for a progress report.

-And so in those amendments, you justify any changes that are potentially required for your project. And once again, these amendments go through the review process. Until the research ethics officer and the researcher they agree on what needs to be undertaken to ensure the integrity of conducted research and then those amendments are also approved. So, here it is, I think worthwhile to mention that some projects may be exempt from seeking ethical clearance. 

-And usually the projects that get this opportunity are the projects that deal with the data that is freely available, for example through the internet. However, exemptions are granted on a case by case basis and usually they depend on whether the data that is going to be used is identifiable and whether we can trace it back to a particular individual. And those exemptions are granted through an application process as well. 

-Okay, so now that we have talked at length about ethical responsibilities to individuals in a research setting, let's shift gears and talk about some Integrity obligations to serve as recipients or clients. And today we're going to focus in particular on the context of interpreting and translation. 

-So the things that we need to take into account in this context is first and foremost, accountability and professionalism have an interpreter or a translator. So what that means is that we need to only accept assignments that are appropriate for the training and expertise that we currently possess, at the time that we begin this assignment, both in terms of the subject or setting, and also in terms of language fluency. 

-Just like with research, it is of utmost importance to consider the confidentiality of our clients, especially in the context of interpreting. Because interpreting can take place in a fairly high stakes or sensitive environments, such as, for example, political negotiations, business negotiations, or medical contexts, where the clients are sharing sensitive and often traumatic information with the interpreter.

-It was always crucial to maintain accuracy and impartiality when you're performing your duties as an interpreter or translator. So your primary goal is to convey somebody's message accurately. And what it means is that you have to divorce it from your own feelings and opinions. So even if you know that a particular statement is not truthful, or it contains mistakes, you still need to translate or interpret it faithfully, according to the message that has been originally conveyed by the speaker.

-Finally, when you're hired as an interpreter or a translator, it's not just because your knowledge of the two languages that are at play, but also because you're aware of the cultural sensitivities, and cultural peculiarities. And so what you need to be aware of is any cultural differences that may potentially interfere with effective and clear communication. 
-If a situation arises where that seems to be the case, it is your responsibility to do what you can to help your clients bridge the misunderstanding. So such situations may arise with, for example, the use of humor, which is notoriously difficult to accurately interpret. And we're concluding this first part of the lecture by discussing the ethical responsibilities we as instructors have to our students. 

-And these obligations are applicable in a variety of teaching and learning contexts, whether we're talking about higher education, or a school setting, and we're including teasle practice in this as well. So our core responsibility is the duty of care, which means that when we're teaching group of students, their learning experience should be our priority, and that they should feel safe and encouraged to express their opinions in an environment that is non judgmental, and that the environment that we create in the classroom should be really conducive                            to productive and an effective learning experience.

-As instructors, we also need to ensure that we provide all of our students with equal and fair opportunity to learn and to engage with the learning materials that we're providing them with. So here, it means that we should treat and judge our students based exclusively on their learning progress and performance, rather than on any of the pre existing biases that we may have to other irrelevant factors such as, for example, gender, or ethnic background, or language ability. 

-different issues or problems that students may share with an instructor need to be treated with integrity and confidentiality, which is something that you see is a common thread that comes through ethical considerations and research professional practice. And now in teaching practice, as well. We also need to exercise great awareness and sensitivity to different our individual our needs and adapt our teaching methods and materials accordingly. 

-So this is especially crucial when we are dealing with a group of students that come from different backgrounds, whether cultural, religious, or linguistic. And when we're teaching students have different levels of for example, English proficiency. So our teaching methods need to be adjustable and flexible so that they're able to assist the students and meet them where they are. Then finally, because as we have already discussed, a teacher and the student exists in a situation where there is an imbalance of power and influence, and instructors should never take an opportunity to in any way exercise or abuse this imbalance of power because that would put a student in a very uncomfortable position, and that would go against all of the guidelines of ethical conduct. 

-Okay, so now that we have an understanding about ethical research and professional engagement with individuals, let's move on to the responsibilities we may have to broader communities. Obviously, working with languages and cultures are doing literally studies has an impact on public attitudes and perceptions towards the larger community your work has been affiliated with. Therefore, it is extremely important to approach your work with an awareness of and sensitivity to community norms, values, morals and taboos. 

-You also should aim to accurately and faithfully represent that community. Just like with potential research risks or cultural misunderstandings in an interpreting context, it is important to anticipate and mitigate any potential misinterpretations of your work. Finally, it is also crucial to communicate and disseminate your information in an accountable and responsible manner. 

-This obviously involves not falsifying or fabricating any aspect of your work, such as research results, for example, being very cautious not to overgeneralize any of your research findings, and exercising great transparency in reporting any financial support and potential conflicts of interest may that may have influenced your results. Remember, when you aim to reach a wider audience, and communicate your professional expertise to the public, you need to estimate the integrity of your selected outlet as well. 

-One of the outlets that I can recommend is the conversation, which is the online platform, which aims to present recent academic findings in an accessible manner without sacrificing academic rigor and ethical practices. Since it is highly unlikely that we will be undertaking any research projects as individuals without any explicit affiliation to a research institution, or practicing teaching or interpreting and translation without any official accreditation. In addition to the responsibilities we have as individuals and broader communities. 

-We also have obligations to the organizations where either a part of or the organizations that we work collaboratively with. So this section, we're going to begin by discussing our responsibilities to the institutions we represent. And as an example, we're going to use the University of Queensland. 

-So, as the members of UQ staff and student bodies we’re expected to act with integrity, and to uphold the university's mission, vision and values through complying with the policies and procedures outlined in the code of conduct. So the university's mission statement includes the pursuit of excellence in education and research, and excellence in an educational context, by definition, means employment of ethical practices, and exercising academic integrity. 

-I would also like to draw your attention to one UQ value in particular, which is the value of honesty and accountability, since this is the one that is the most relevant to the context of today's lecture. And so this value states that we act with integrity and professionalism and uphold the highest ethical standards, we are committed to transparency, and accountability. 

-Our decisions ensure responsible stewardship of the university's resources, reputation and values will lead by example, in all areas, including our approaches to sustainability. And so to specify these values further, the University actually outlines some ethical principles in its code of conduct. 

-And so the ethical principles are integrity and impartiality, promoting the public good, which pulls us back to the fact that our research or our public services, our professional engagements should be for the benefit, if not the people who were directly engaged with them for the benefit of the larger community, a commitment to the system of government accountability and transparency. So all of those terms we have covered earlier in this lecture. And they should remind us of our responsibilities to the communities and to the individuals.

Now, moving on from the responsibility to the institution that you represent the responsibility to some external organizations. And these organizations include relationships with sponsors, funding organizations, industry clients, government and private sector institutions. 

-So when you building collaborative relationships with any of those organizations, what you need to ensure is that you maintain your academic and professional integrity, and that you're making sure that the funding body does not skew your ethical practices and does not influence your approach to academic or professional integrity. And it is also important to negotiate a boundary with this funding body. 

-So for example, who has the publication rights if we're talking about research context, who has the ownership of the data. An example I would like to give here is, for example, a second language acquisition research of collaborating with Duolingo as the funding organization that provides funds for a research project investigating whether Duolingo is an effective method of self studying second language. 

-And so basically, what needs to take place prior to the researcher agreeing to undertake the study or to accepting those funds is a clear message about the fact that their ethical practices are not going to be influenced by obtaining the funds from the company itself. So it means that whether the results are positive, suggesting that Duolingo is an effective method of second language acquisition, or for example, neutral to negative, meaning that using Duolingo has minimal to no impact on successful language, second language acquisition, those various outcomes would not influence the availability of the funds. 

-Okay, so now we're moving on from discussing ethics to integrity proper. And we begin this topic by looking at our responsibilities to our colleagues and peers, whether in academic or professional contexts. And because we're all in the setting of the university, we're going to start with an example of being a up student, and what kinds of expectations entails in terms of integrity. So, as a UK student, you're expected to act honestly and ethically in all the academic work, including assessment tasks. 

-And you achieve this by giving appropriate recognition to any direct quotes that you use from other authors, or to those authors whose work has made an intellectual contribution to the contents of your work through appropriate referencing. 

-You also are doing it through acknowledging shared ownership of ideas and contributions to group projects, or group assessment tasks. And finally, you need to take active measures to avoid academic misconduct, such as plagiarism and collusion. 

-So in this lecture, we're going to focus on plagiarism in particular. So one way of defining plagiarism would write thinking about is when you use somebody else's ideas without showing clearly where they came from, or when you pretend that they're actually your own ideas. 

-For instance, in cases such as when you're handing in somebody else's work as your own, or when you're copying words or ideas from someone else without giving them appropriate credit through referencing, when you're failing to use quotation marks when you use somebody else's words, and you directly quote those words rather than paraphrase when you're giving incorrect information about the source of a quotation when you change a few words in the sentence, but leave the rest of it the same with or without crediting the source. So you're under paraphrasing, and you're copying so many words or ideas from a source that makes up the majority of your work, whether you give credit or not. 

-And finally, when you're handing in work that you already used for another assignment, which is a particular case of plagiarism, known as self plagiarism. So current software gives us ample opportunity for plagiarism detection. 

-So for example, your research proposals will be submitted through Turnitin which detects any similarity to other sources that are available online, and this software is producing reports not only on how much of the information that you use has been taken from other sources, but also the precise sources that this information has been taken from. However, what I would like to say is that, if you  see the similarity percentages being higher in comparison to what you would like them to be, this is not necessarily the reason for you to be worried as all that matches are picked up by the software.

-So for example, if you employ appropriate referencing 2010 is going to highlight those references as being a match to some other pre existing sources. Additionally, turn it in highlights all quotations that you use, irrespective of whether you provide appropriate attribution, or you don't provide such an attribution. So sometimes, a particular submission may have a higher similarity percentage, but it still means that previous sources have been treated with respect and integrity. 

-And sometimes there is a low similarity percentage, but it still means that other work has largely been using sources without proper attribution. In a professional context, fair distribution of work opportunities and resources are among some of the obligations that we have to our colleagues. So that means that the workload and the tasks responsibilities, opportunities are shared equally among the collaborators within the particular team. We're also looking at negotiating roles and responsibilities in advance of undertaking a particular task, and everybody being really clear on what they are supposed to be doing. 

-So, for instance, here we may attribute this particular point to, for example, an opportunity to co author a paper or to collaborate on a particular project. And finally, here will also highlight the importance of maintenance of work health
and safety as a working environment, just like learning environments should be really conducive to productive and safe engagement with your task at hand and with your colleagues. 

-Our discussion of academic and professional integrity would have been incomplete if we haven't touched on the responsibilities we have to the field. So even though it may sound quite abstract, what that means is that as a representative of a particular research field or professional engagement, it's our task to support and sustain this research and professional culture. And we can do it in a variety of different ways. So for instance, it is always important to maintain high standard and transparency of your own work, and leading by example, so to say. So for instance, recently, open access data repositories became exceedingly popular in research. 

-So that means that after you have conducted your study, you may upload your data sets was a quantitative or qualitative online so that other researchers can access your data, verify your findings, and then replicate your studies. You may also want to consider professional development and opportunities to stay current on your area of expertise. So in research, it means keeping up to date with developments in the fields and the most recent findings, ensuring that what you're doing is still the best practice in your research area. 

-And for example, TESOL practitioners or interpreters and translators. It means participation and seeking out professional development opportunities. Finally, supporting research and professional culture can be achieved through taking on a variety of service roles and therefore mentoring your peers, your colleagues, and also, for example, students if we're talking about a research context. 

-So the service roles come in a variety of different shapes and they may manifest themselves as supervision roles, training and mentorship, conference organization, engagement in peer review process, and professional memberships, where the professionals and researchers from the same field come together and share their experiences and their knowledge on the Most current ethical practices and conduct with integrity. So as always, let's conclude today's lecture by discussing the key points that we were able to cover. 

-And I would like to start this lecture summary by addressing some of the very common misconceptions that people hold about ethics and integrity. And the first of these misconceptions is that ethical code of conduct is exclusive to research. So what I hope you were able to see in today's lecture is that ethical code permeates many different professional practices, and it's applicable in both research and professional contexts. So therefore, it is not exclusive to academia. 

-Furthermore, even if you do not work with people or do not plan to work with people, there are still aspects of ethical conduct that you need to be aware of, and to actively exercise. Today we have broken down the general concept of integrity as a set of obligations to others. 

-And we have looked at our obligations to individuals, communities, organizations, and the field we represent itself, however, and perhaps even more importantly, acting with integrity is responsibility to yourself to do the right thing. Thank you for your time today and we’ll see you next week!

