# Action Research in the Classroom


-Hi, everyone. Our topic this week is action research. And we're going to start by discussing how we situate action research within the framework, the general juxtaposes basic research and applied research. In this part, we will also discuss the definition of action research and some of the assumptions that are made about this particular area of research inquiry.

-Then we'll talk about examples of action research in our everyday life. And then the third part is going to be about the use of action research framework to improve professional and academic practices, in particular, will focus on action research in education. And this is the part where we're going to look at the action research cycle, and then we will take it to other areas in social sciences and applied linguistics. Specifically, we will look at action research in interpreting and translation studies. And then we will consider how action research practices are applied in academia. I hope you find today's lecture interesting. And without further ado,let's begin.

-So to provide an adequate definition for action research, we first need to understand how it fits with basic research, applied research. And how's the three research types are interrelated. So let's begin with looking at basic research. The goal of basic research is generally speaking to advance our knowledge or to generate new ideas and insights. Even though basic research is often characterized as being science for the sake of science, it does have public benefit in and of itself by increasing our understanding of certain phenomenon.

-And so an example of basic research could be something like investigating cultural differences in negotiation strategies. So here you may notice that this type of research doesn't target a particular group or a particular context for negotiation. Moving on to applied research, he will say that often leads to practical outcomes. So here we're also aiming to offer some public benefit, but we have a more specific focus on particular groups and communities.

-So narrowing down the topic above, we can say that an applied study may look at something like linguistic realisation of cultural differences in professional negotiations, still quite broad, but it may be informative for the audience that is interested in improving the negotiations within corporate culture. And then finally, action research results in concrete and actionable solutions. Usually, action studies have direct benefit to a smaller community, an organization or an individual. So here we may look at the influence of cultural background of the students who are taking this course on their particular behaviors, such as requests for clarification, and engagement with feedback. conducting a study on this topic will benefit a small community of the students who are taking our course and myself as an individual who is the course coordinator.
 



-So keeping that in mind, let's provide a definition for action research. Action Research is a reflective process, either introspective, which means that it comes from the researcher practitioner from within for extra spective, which means that it comes from other people that are in the environment in which the Akron research study is conducted, in which professionals examine their own practice systematically and carefully using the rigor techniques and procedures adopted in academic research.

-So to unpack this definition a little bit, let's consider the following two examples. If I'm thinking about our previous tutorial, this is not action research, even though it is a reflective and an introspective process, because it lacks the systematicity and rigor that is expected from academic research. It's just a one time thing, right? I'm just thinking about this one time, and it's not clear whether I'm employing any particular techniques.

-However, if I'm recording my reflections on a weekly basis, and they use different qualitative and quantitative research tools, I'm engaging in action research. So the question I would like to ask you here is, what kinds of qualitative and quantitative techniques and measurements can I employ when I conduct my action research on our tutorials, so this is something that we're going to come back to in our tutorial.

-This is the question that we'll begin our discussion with. So now that we know what action research is, let's make it very clear what action research is not concerned with. And action research is not interested in providing a comprehensive overview on the topic of interest, unlike, for example, library research or literature review, so there is no expectation or no prerequisite to become extensively familiar with previous studies on a particular topic.

-Additionally, action research is not concerned with answering why we do or have been doing certain things in a certain way, unlike qualitative research, so we're not focusing on the practices that are already in place. But rather, we're focusing on potential improvement and refinement of those practices. So the orientation of action research is not to the past or the present, but to the future.

-And finally, it is important to say that action research is not interested in aiming to prove a hypothesis by conducting research on or about human behavior. So we're not trying to observe how people do certain things, unlike empirical studies, and we're not aiming to prove a particular theory, but rather, we're finding solutions that are specific and useful for the concrete situation that the researcher practitioner finds themselves in.

-Okay, so let's conclude this part of the lecture by going through the assumptions of action research. And the first assumption is that practitioners or professionals would work best on problems and issues that are relevant directly to their practice. So this means that a professional would usually lack the time or
 



perhaps the motivation to engage in theoretical research inquiry. However, if there is an issue that is directly relevant to improving their practice, they may be more engaged in attempting to find the solution for it.

-The next assumption is that examining and assessing your own work, and then considering ways of working differently, is a natural process, and also an essential component for professional development. So this assumption sees change and innovation as positive practices, and therefore by encouraging the employees to engage in action research, such practices are also encouraged. And then finally, we can talk about undertaking action research as gateway for improved collegiality and collaboration.

-So let's consider a situation in which a practitioner has identified an issue that's relevant to their practice. When they talk about a piece about this issue, it may be the case that they have experienced with this same problem. Therefore, such situation would open up opportunities for conducting collaborative action research projects.

-So in some action research is viewed as an extremely positive and productive professional practice. And many workplaces are encouraging their employees to engage in action research. This is good news for us. Because even if you're not planning to pursue research as a career path as a tools and techniques that we have been learning about in terms of different qualitative and quantitative studies, may come in handy for you in future as a professional.

-To get a clearer picture of what action research entails. And looks like let's turn to some daily life examples. And the assertion I would like to make here is that action research is everywhere. So consider a scenario in which you have recently received a delivery that was made by Australia Post, it is very likely that as a follow up, you will also receive an email asking you about this experience and also asking whether you're likely to recommend the services of Australia Post to a family member or a friend. And in this email, you will get a scale from zero to 10. Not at all likely to extremely likely This is an example of action research.

-And it is done with a purpose to improve Australia Post delivery services or to find out whether there is anything that needs changing or looking into. Similarly, if you engage with any customer service representatives for a company that you are in some way affiliated with as a follow up to your conversation or to the services that they have been providing you. You are very likely to receive A similar questionnaire that asks you about the quality of the help you received. And this is usually undertaken with the purpose of training a particular customer representative member that has been working with you.
 



-In a similar vein, as students at a university, you participate in action research quite frequently, actually each semester by filling in your student feedback forms, both on the course in general and on specific teaching staff members that have been engaging with you throughout the semester. In this tutorial, we will look at such feedback forms in greater depth, and in particular, we will be focusing on addressing the following questions. Is it intro or extra spective? research? What kinds of data is collected qualitative or quantitative? What implications does this type of action research have? And how are those implications communicated to a wider community of students or teaching colleagues.

-And finally, think about whether you would like to suggest any improvements to this particular research design? So as I said, keep those questions in mind as that some things that we will return to in our tutorial. If we look at social sciences, the framework of action research has been predominantly adopted in the area of education.

-This is because teaching by its nature is a reflective process in which practitioners whether they are in the school system in higher education, or in the context of second language learning and teaching, routinely engage in problem solving, and pedagogical innovation.
-So the teachers ask themselves questions about creative and informative content design, appropriate delivery methods, and best ways to support this students, such as questions like How should I introduce this topic? Who should I call on to answer this question? How do I improve in class engagement?

-And how do I adjust existing materials to suit the needs of my students? This process of innovation and fine tuning doesn't stop at the stage of curriculum planning and design, but is rather characterized as being ongoing as it happens during class delivery as well.

-Nonetheless, the teachers judgments on what's considered to be the best practice are always made intuitively based on their experiences are implemented with low feedback from either peers, students or higher management are constrained by the time and the resources available, and therefore, rarely lead to lasting changes in institutions curriculum assessment, learning process or policy.

-All of this makes action research and natural fit was educators desire and necessity to innovate, as it provides concrete framework that formalizes and records the reflective practice, thus making it more sustainable and making it more likely to be implemented long term.

-Even though action research has been shown to be fruitful in resolving specific classroom issues, at first, it was viewed as mere teacher reflection, and not as empirical research. However, over time, this perception has shifted. And now it is accepted that if action research in education is undertaken with
 



appropriate academic rigor, it can be considered a research methodology in its own right, as it can supply knowledge regarding localized problems and suggest useful, targeted responses. Action

-Research in education can be useful and fruitful when we talk about the following issues that can occur in such context, classroom management, and here we can talk about implementation of group work or maybe the use of technology in the classroom, development of learning materials. So for instance, appropriate use of audio visual support, sequencing and structuring the curriculum, particular teaching areas so for example, the most efficient methods on instructing on oral skill development or reading, student behavior, achievement, motivation, engagement with content and personal management issues such as time management, relationships with colleagues and higher management.

-So the process of conducting action research in education is usually described as a cycle where an initial resolution of a problem necessitates further consideration and refinement, you may find it helpful to think about action research cycle in the same way you would think about visiting a GP, where a common problem in the classroom environment is first identified and diagnosed. And then an appropriate solution is prescribed, tested, and its effectiveness evaluated as a result. So the actual research process in education and in other fields as well, falls into three different stages. And in this lecture, we're going to go through the stages using an example of poor academic integrity practices among students, and frequent cases of plagiarism.

-So let's say this is the problem that you have identified in your classroom. How are you going to resolve it, employing the action research framework? So in the first stage, otherwise known as the planning or the diagnostic stage, you first check for symptoms? In other words, how do you know that there are indeed poor academic contemporary practices among your students? How were you able to identify the cases of plagiarism? So here, let's say your students have made a recent submission, where it became apparent that the work of previous authors is either not acknowledged, appropriately, or not acknowledged at all.

-So that suggests to you that students actually find it quite difficult to use APA referencing style appropriately, after you have checked for symptoms and ascertained that there is enough evidence to suggest that the problem indeed exists, you suggest the cause for that problem. So here are you may want to think about factors like APA guide being quite overwhelming for novice students, especially those who have just been introduced to the idea of referencing. And so therefore, it's not surprising that they find it quite challenging to use it appropriately.
 



-So this is the conclusion of the planning stage, you have identified and found evidence for the problem. And then you have also suggested a potential reason behind that perform. Now you're moving into the second stage, which is taking action or suggesting treatment or an intervention solution.

-So here when we choose to give our students advice on using a software that manages citations, such as EndNote, and Mendeley, we may advise them to come and see their lecturer or tutor or librarian for extra help. Or we may even want to dedicate specific time in our class, to discuss academic integrity, ethical research, plagiarism, an APA referencing style, in particular, with concrete examples, and a demonstration.

-So after you have taken this action, you need to evaluate whether the treatment or the intervention has been successful. So for instance, you may want to assign another written essay or a submission of some sort to evaluate whether the APA referencing style used has improved among the same group of students. And your evaluation will influence the next cycle of action research.

-So let's say, of the method that you have employed in the second stage has indeed proven to be quite fruitful. So when we move back to the planning stage, we may, we may want to incorporate that solution into our curriculum. So there may be a new dedicated tutorial in our semester plan that is going to be focused specifically on AP referencing, and then you go into the second cycle of action research, testing that solution out with the second group of students in the follow up semester. On the other hand, if you're taking action solution was not successful, you go in and develop an alternative solution by engaging in the planning stage.

-So perhaps suggesting a different cause, and therefore proposing a different course of action to remedy the problem. So I know that a lot of you are interested in teaching English as second language, or perhaps teaching heritage greens, your languages. And if that's the case, I would highly recommend the work of professor and burns, who specializes in action research in teasle. I have uploaded a couple of her talks and interviews to our Blackboard site.

-So when you do have a moment, please make sure to check them out. So even though for the past few decades, action research has been quite firmly rooted in the field of educational research specifically, it is possible to extrapolate It's frameworks and principles beyond education.
-In this section, we will discuss how action research applies to interpreting and translation studies, and improving academic practices. When we'll look at action research in interpreting and translation, the first thing that's important to point out is that it's a relatively young field much younger than its educational counterpart. However, there is a strong connection between the two.
 



-This means that the main focus of action research in interpreting and translation to date has been on developing and tailoring new approaches to contextualize interpreter and translator training. One notable study for instance, looked at collaborative curriculum planning and development and the trial course delivery for interpreting into and from languages have limited diffusion and distribution in Australia, which is a very important area of investigation.

-Nonetheless, it is important to remember that action research practices can and also need to be applied to improve professional practice in and of itself, rather than just training in becoming a professional interpreter and translator, and that seems to be a very promising research field. When we consider action research in academia, broadly speaking, we can define it is any activity that is aimed at improving academic practices.

-And in saying that, I mean that action research in academia encourages and safeguards compliance with academic integrity and ethical research. So it can be manifested through developing formalized educational tools to train students and nervous academics observe principles of ethical research, and proper academic conduct. It is also manifested through maintaining quality of education, and encouraging change and innovation in curriculum design, through transparent and consistent evaluation at ACU.

-This is achieved through the work of Institute for Teaching and Learning innovation, otherwise known as Italy, which is in charge of administrating the student evaluations. We can also identify the traits of action research in academia in supporting fair and equitable career progression and professional development practices. at UK it is once again is done through the work of Italy. So for instance, last year, I participated in professional learning pathways working group that brought together researchers from different backgrounds and at different stages of their careers to identify the most efficient pathways for them to be able to develop personally and grow professionally.

-Finally, action research is seen through simply adjusting and fine tuning research methods to best suit the target research context, and participants under investigation. Alright, so let's recap three key points of today's lecture. So action research can be defined as a research paradigm that's conducted by the researcher practitioner, and for the researcher practitioner, and their immediate environment, which means that there is no disconnect between the conceptualization and the practical implementation of a certain project, if you will, the thinker and the doula are combined into a single person, or into a single group of people who are undertaking a research project.
 



-And as with many other types of research, we can identify the pros and the cons of action research, and we're going to start with the pros. So first of all, action research is result oriented, which means that it leads to practical innovation.
-However, it's also important to understand that sometimes, action research leads to theoretical insights as well, so it's impossible to truly separated from basic and applied research. Furthermore, action research is accessible to professionals in various fields and not necessarily researchers that received specialized training. Finally, action research provides a gateway to a more meaningful engagement and understanding with one's field to professional growth, and also to collaboration opportunities. Now, on to the cons.

-Action Research is often specific to a particular context, though it is sometimes possible to generalize from that. It is also something that presents a challenge for the professionals given the scarcity of time and resources. So usually it requires additional effort. But to be able to engage in action research.
Finally, action research is often described as lacking statistical analysis, which leads to reflective and descriptive rather than justified and precise conclusions.
